### ISSUE TITLE
Didn't show up in ADDON listing

### ISSUE THREAD

**Issue by Canisbiggus** [fizzwidget/zippy-lighter#1]
Installed this morning - deleted the older (ver 6) subdirectory. Didn't show up in the listing when the game launched and wasn't attaching as a button to fire.  Also installed scrollmaker and that didn't pop either.

Love both these addons and thanks for updating them.
8-)

**Comment by Canisbiggus** [comment]
Found the fix - recoded the folder to GFW_ZippyLighter - loaded back into the ADDON drop downs and is there when the cooking screen opens - no LUA errors.

Assume ScrollMaker will fix the same way - again thanks again for great addons.
8-)

**Comment by fizzwidget** [comment]
The zip files have the wrong implicit folder name, so the addons don't come out as `GFW_DiggerAid`, `GFW_FactionFriend`, etc the way they're supposed to, which prevents them from loading. (That'll teach me to let Github make my zip files.) 

I can't easily fix the zip files already here (I'll look into it), but if you re-download from www.wowinterface.com or www.fizwidget.com you'll get the right stuff now.
