### ISSUE TITLE
Error when opening cooking window.

### ISSUE THREAD

**Issue by Baltezar** [fizzwidget/zippy-lighter#2]
I get this error when I open the cooking window.

2x attempt to concatenate a nil value
[C]: in function `strjoin'
GFW_ZippyLighter\ZippyLighter.lua:280: in function `FZL_DetectMethod'
GFW_ZippyLighter\ZippyLighter.lua:40: in function <GFW_ZippyLighter\ZippyLighter.lua:23>

Locals:
(*temporary) = ":"
(*temporary) = "item"
(*temporary) = ":"
(*temporary) = 70722
(*temporary) = ":"
(*temporary) = nil
(*temporary) = ":"
(*temporary) = nil

There is no tab to the side with the cooking fires etc. But if I close it and open it again no error and then the tab is there.

**Comment by Baltezar** [comment]
sorry for the double comments.

**Comment by fizzwidget** [comment]
Haven't been able to reproduce this aside.
